// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LBGPS
{
        public const string achievement_20_score = "CgkItpiq1OgVEAIQAw"; // <GPGSID>
        public const string achievement_1_line = "CgkItpiq1OgVEAIQDQ"; // <GPGSID>
        public const string leaderboard_top_score_hoop = "CgkItpiq1OgVEAIQCg"; // <GPGSID>
        public const string leaderboard_top_score_protect = "CgkItpiq1OgVEAIQCw"; // <GPGSID>
        public const string achievement_1_ball = "CgkItpiq1OgVEAIQDA"; // <GPGSID>
        public const string achievement_50_score = "CgkItpiq1OgVEAIQBA"; // <GPGSID>
        public const string achievement_100_games = "CgkItpiq1OgVEAIQBg"; // <GPGSID>
        public const string achievement_100_score = "CgkItpiq1OgVEAIQBQ"; // <GPGSID>
        public const string achievement_500_games = "CgkItpiq1OgVEAIQBw"; // <GPGSID>
        public const string leaderboard_top_score_gap = "CgkItpiq1OgVEAIQCQ"; // <GPGSID>
        public const string achievement_1000_games = "CgkItpiq1OgVEAIQCA"; // <GPGSID>
        public const string leaderboard_top_score_classic = "CgkItpiq1OgVEAIQDw"; // <GPGSID>

}

